name: Terraform AWS Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:

    - name: Repository auschecken
      uses: actions/checkout@v3

    - name: AWS Zugang konfigurieren
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::569791157629:role/LabRole
        aws-region: us-east-1

    - name: Terraform installieren
      uses: hashicorp/setup-terraform@v2

    - name: Terraform init
      run: terraform init

    - name: Terraform apply
      run: terraform apply -auto-approve
